wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1649166629
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 33
      2:
      - 1
      - 2
      - 3
      - 5
      - 33
      3:
      - 2
      - 3
      - 8
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
